#! /bin/sh
#
# Start PostgreSQL on the recovery target node
#
if [ $# -ne 2 ]
then
    echo "pgpool_remote_start remote_host remote_datadir"
    exit 1
fi

DEST=$1
DESTDIR=$2
PGCTL=/usr/pgsql-9.3/bin/pg_ctl

ssh -T $DEST -p 49154 $PGCTL -w -D $DESTDIR start 2>$DESTDIR/startup.log 1>$DESTDIR/startup.log >$DESTDIR/startup.log  < /dev/null &
