postgres:
  image: dockerrepo:5000/arrs/arrs-cloud-base-postgres:1.3.0.39
  stdin_open: true
  tty: true
  restart: always
  log_driver: "json-file"
  log_opt:
   max-size: "100m"
   max-file: "10"
  ports:
  - "5432:5432"
  - "49154:49154"
  environment:
  - HOST_IP=HOST_IP_MACRO
  - HOST_NAME=HOST_NAME_MACRO
  - MONITOR_PORT=8175
  volumes:
  - /opt/etcd/config:/opt/etcd/config
  - /usr/local/docker/pgsql/data:/var/lib/pgsql/9.3/data
  - /var/log/postgres:/var/log/postgres
  - /var/log/postgresDocker:/tmp

appObserverPostgres:
  image: dockerrepo:5000/arrs/arrs-cloud-base-app-observer:2.0.0.3
  restart: always
  log_driver: "json-file"
  log_opt:
   max-size: "100m"
   max-file: "10"
  ports:
   - "8175:8175"
   - "8177:8177"
  environment:
   SECURE_PORT: 8175
   NON_SECURE_PORT: 8177
   PRODUCT_NAME: ACP-POSTGRES
   APP_WEBSERVICE_FQDN: HOST_IP_MACRO
   APP_WEBSERVICE_PORT: 7501
  volumes:
   - /var/opt/app-observer-postgres/config:/opt/app-observer/conf/external
   - /var/opt/app-observer-postgres/logs:/opt/app-observer/logs

postgresapp:
  image: dockerrepo:5000/arrs/arrs-cloud-base-postgres-app-monitor:1.2.0.16
  stdin_open: true
  tty: true
  restart: always
  log_driver: "json-file"
  log_opt:
   max-size: "100m"
   max-file: "10"
  ports:
   - "7501:7501"
  environment:
   WS_PORT: 7501
   APP_OBSERVER_PORT: 8177
   PG_PORT: 5432
   PG_USER: "pgpool_checker"
   HOST_IP: HOST_IP_MACRO
   HOST_NAME: HOST_NAME_MACRO    
  volumes:
   - /usr/sbin:/usr/local/sbin
   - /var/log/app_monitor/postgres:/tmp
   - /var/opt/app-monitor-postgres/perf_monitor/logs:/opt/perf_monitor/logs
   - /var/opt/app-monitor-postgres/status_monitor/logs:/opt/status_monitor/logs
   
keymanager:
  image: dockerrepo:5000/arrs/arrs-cloud-base-keymanager:1.0.0.9
  stdin_open: true
  tty: true
  log_driver: "json-file"
  log_opt:
   max-size: "100m"
   max-file: "10"
  environment:
  - HOST_IP=HOST_IP_MACRO
  - HOST_NAME=HOST_NAME_MACRO
  volumes:
   - /var/log:/tmp
  volumes_from:
  - postgres   

logstashforwarder:
  image: dockerrepo:5000/arrs/arrs-cloud-base-logstash-forwarder:2.0.0.4
  restart: always
  log_driver: "json-file"
  log_opt:
   max-size: "100m"
   max-file: "10"
  environment:
   LS_HEAP_SIZE: 1g
   CA_CERT_LOCATION: /etc/elk-keys/ca.pem
   ES_HOST: ELK_DNSNAME_MACRO
   NODE_NAME: HOST_IP_MACRO
  volumes:
   - /var/opt/logstash-forwarder/log:/var/log/supervisor
   - /var/opt/logstash-forwarder/conf:/etc/logstash-forwarder
   - /var/opt/logstash-forwarder/keys:/etc/elk-keys
   - /etc/localtime:/etc/localtime:ro
   - /var/opt/:/var/opt/
  volumes_from:
   - postgres  
   - appObserverPostgres
